[theme]
# Primary accent color (CWC Vibrant Green)
primaryColor = "#77BA43" 

# Background color for the main app (Clean white)
backgroundColor = "#FFFFFF" 

# Background color for the sidebar (Light gray to make the green pop)
secondaryBackgroundColor = "#F4F4F4" 

# Text color (CWC Charcoal Gray instead of standard black)
textColor = "#464646" 

# Font family (We will override this with Montserrat in the CSS, but this is a good fallback)
font = "sans serif"
